"""Run the local suite and publish the *evidence*, not the tests.

`tests/` is local-only by design, so CI cannot vouch for it. The gap that
leaves is real: without something, a release's test claim rests on whatever
number somebody last typed into a summary file. That is not hypothetical --
`tofu-final-summary.txt` published 1,544 backend tests against a tree that
collected 168.

This closes the gap without publishing the tests. It runs the real suite,
captures what actually happened, and writes a committed artifact:

    evidence/test-run.json

The artifact records the commit it ran against, so a stale one is detectable
rather than merely old. Anything that quotes a test count -- release notes,
README, the architecture inventory -- should read it from here rather than
restating it, which is P2.17.

Usage:
    .venv/Scripts/python scripts/record_test_evidence.py
    .venv/Scripts/python scripts/record_test_evidence.py --check
"""
from __future__ import annotations

import argparse
import json
import platform
import re
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EVIDENCE = ROOT / "evidence" / "test-run.json"

# pytest's terse summary line, e.g. "168 passed, 1 skipped, 2 warnings in 24.35s"
_SUMMARY = re.compile(
    r"(?:(?P<passed>\d+) passed)?"
    r"(?:, )?(?:(?P<failed>\d+) failed)?"
    r"(?:, )?(?:(?P<skipped>\d+) skipped)?"
    r"(?:, )?(?:(?P<errors>\d+) error)?"
)


def _git(*args: str) -> str:
    try:
        return subprocess.check_output(
            ["git", *args], cwd=ROOT, text=True, stderr=subprocess.DEVNULL
        ).strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return ""


def _parse_counts(output: str) -> dict[str, int]:
    counts = {"passed": 0, "failed": 0, "skipped": 0, "errors": 0}
    for line in reversed(output.splitlines()):
        if " passed" in line or " failed" in line or " error" in line:
            m = _SUMMARY.search(line)
            if m:
                for key in counts:
                    if m.group(key):
                        counts[key] = int(m.group(key))
                return counts
    return counts


def run() -> dict:
    print("running the local suite (this is the real thing, not a smoke check)...")
    proc = subprocess.run(
        [sys.executable, "-m", "pytest", "tests/", "-q", "-p", "no:cacheprovider"],
        cwd=ROOT,
        text=True,
        capture_output=True,
    )
    output = proc.stdout + proc.stderr
    print(output.splitlines()[-1] if output.splitlines() else "(no output)")

    counts = _parse_counts(output)
    dirty = bool(_git("status", "--porcelain"))

    return {
        "schema": 1,
        "note": (
            "Generated by scripts/record_test_evidence.py. The tests themselves "
            "are local-only by design; this artifact is the published evidence "
            "that they ran. Do not hand-edit -- a typed number here is exactly "
            "the failure this file exists to prevent."
        ),
        "recorded_utc": datetime.now(UTC).isoformat(timespec="seconds"),
        "commit": _git("rev-parse", "HEAD"),
        "branch": _git("rev-parse", "--abbrev-ref", "HEAD"),
        "working_tree_clean": not dirty,
        "python": platform.python_version(),
        "platform": f"{platform.system()} {platform.release()}",
        "exit_code": proc.returncode,
        "green": proc.returncode == 0,
        "counts": counts,
        "total_collected": sum(counts.values()),
    }


def check() -> int:
    """Verify the recorded evidence is green and matches the current commit."""
    if not EVIDENCE.exists():
        print(f"FAIL: no evidence at {EVIDENCE}. Run this script without --check.")
        return 1

    data = json.loads(EVIDENCE.read_text(encoding="utf-8"))
    head = _git("rev-parse", "HEAD")
    problems = []

    if not data.get("green"):
        problems.append(f"recorded run was NOT green (exit {data.get('exit_code')})")
    if data.get("commit") != head:
        problems.append(
            f"evidence is for commit {data.get('commit', '?')[:8]}, HEAD is "
            f"{head[:8]} -- re-record before releasing"
        )
    if not data.get("working_tree_clean"):
        problems.append("recorded run had a dirty working tree")

    if problems:
        print("test evidence is not release-ready:")
        for p in problems:
            print(f"  - {p}")
        return 1

    c = data["counts"]
    print(
        f"evidence OK: {c['passed']} passed, {c['skipped']} skipped at "
        f"{data['commit'][:8]} ({data['recorded_utc']})"
    )
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument(
        "--check",
        action="store_true",
        help="verify existing evidence is green and current, without re-running",
    )
    args = ap.parse_args()

    if args.check:
        return check()

    data = run()
    EVIDENCE.parent.mkdir(parents=True, exist_ok=True)
    EVIDENCE.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    print(f"\nwrote {EVIDENCE}")

    if not data["green"]:
        print("run was NOT green -- the artifact records that faithfully.")
        return 1
    if not data["working_tree_clean"]:
        print(
            "note: working tree was dirty, so this evidence does not describe "
            "the commit alone. Re-record from a clean tree before releasing."
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
